version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    image: stephengrider/multi-nginx
    ports:
      - '3051:80'
  api:
    image: stephengrider/multi-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
    - postgres
  client:
    image: sarik123/client_new
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    image: stephengrider/multi-worker
    depends_on:
    - redis